Maxip32/Tiket-Show-PF

- Tiket-Show-Back/src/controllers/cart.js
- Tiket-Show-Back/src/controllers/users.js
> Rama maxi trabajando

- Tiket-Show-Back/src/utils/index.js
> puse carpetas en front

- Tiket-Show-Back/src/models/User.js
> models user

- Tiket-Show-Back/src/models/Artist.js
- Tiket-Show-Back/src/models/Event.js
- Tiket-Show-Back/src/models/Genre.js
- Tiket-Show-Back/src/models/Places.js
Agregue  algunas tablas , pa ir adelantando.
> Agrego  Modelos de tabla: Artis, Event, Genre, Places

- Ticket-Show-Front/src/App.jsx
- Ticket-Show-Front/src/Views/Landing/Landing.jsx
- Ticket-Show-Front/src/Views/Loading/Loading.jsx
- Ticket-Show-Front/src/components/Card/Card.jsx
- Ticket-Show-Front/src/components/CardContainer/CardsContainer.jsx
-Agregue Landing (estrcutura basica)
-Agregue Loading (estrcutura basica)
- Modifique la ruta del NavBar para que en el Landing no se muestre
> estructura de 2 componentes y mas

- Tiket-Show-Back/index.js
- Tiket-Show-Back/src/db.js
>  back levanta

- Ticket-Show-Front/package-lock.json
- Ticket-Show-Front/package.json
- Ticket-Show-Front/src/App.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormLogin.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormRegister.jsx
- Ticket-Show-Front/src/context/AuthContext.jsx
- Ticket-Show-Front/src/firebase/firebase.config.jsx
- Ticket-Show-Front/src/main.jsx
- Ticket-Show-Front/src/redux/actions/actions.js
- Ticket-Show-Front/src/redux/actions/constants.js
- Ticket-Show-Front/src/redux/store.js
- Ticket-Show-Front/vite.config.js
se agrego firebase login y register
> Rama maxi2

- Ticket-Show-Front/src/components/FormFirebase/FormLogin.jsx
- Ticket-Show-Front/src/components/SearchBar/SearchBar.jsx
- Ticket-Show-Front/src/views/Home/Home.jsx
modifique la search bar
los filtros
un poco las cards ( no pude centrarlas con flex, preguntar a dani)
> cambio en estilos del home

- Ticket-Show-Front/package-lock.json
- Ticket-Show-Front/package.json
- Ticket-Show-Front/src/App.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormArtist.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormLogin.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormRegister.jsx
- Ticket-Show-Front/src/components/NavBar/NavBar.jsx
- Ticket-Show-Front/src/context/AuthContext.jsx
- Ticket-Show-Front/src/firebase/firebase.config.jsx
- Ticket-Show-Front/src/main.jsx
>  login y register probar si les funciona

- Ticket-Show-Front/src/components/FormFirebase/FormLogin.jsx
Login funcionando correctamente y testeado ok
>  Login funcionando testeado ok

- Ticket-Show-Front/package-lock.json
- Ticket-Show-Front/src/App.jsx
- Ticket-Show-Front/src/components/UserProfile/Profileuser.jsx
- Ticket-Show-Front/src/components/UserProfile/Shoppinguser.jsx
- Ticket-Show-Front/src/context/AuthContext.jsx
perfil de user y cambio de nombre
>  Perfil de user

- Ticket-Show-Front/src/Views/Detail/Detail.jsx
- Ticket-Show-Front/src/Views/Home/Home.jsx
- Ticket-Show-Front/src/components/Paypal/Paypal.compra.jsx
- Ticket-Show-Front/src/components/Shoppingcart/Shoppingcart.jsx
- Ticket-Show-Front/src/components/UserProfile/Profileuser.jsx
- Ticket-Show-Front/src/components/UserProfile/Shoppinguser.jsx
- Ticket-Show-Front/src/redux/actions.js
- Ticket-Show-Front/src/redux/reducer.js
estilos parciales en carrito
estilos parciales en perfil
> estilos en carrito y perfil

- Ticket-Show-Front/src/components/UserProfile/Profileuser.jsx
se agrego corrigio error llave de cierre componente profile
>  se agrego corrigio error llave de cierre componente profile

- Ticket-Show-Front/package-lock.json
- Ticket-Show-Front/src/App.jsx
- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
- Ticket-Show-Front/src/components/NavBar/NavBar.jsx
*Agregue a App la ruta Create Event
*Modifique en la NavBar el link hacia Create Event
*Creacion provisional del componente CreateEvent con inputs y estilos
-Falta funcionalidad
> modificacion componentes para crear Eventos

- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
-se ajusto el tamaño del formulario para que no ocupe tanto espacio en la pantalla (desktop)
> ajuste tamaño

- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
>  placeholders cambios minimos

- Ticket-Show-Front/package-lock.json
- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
- Ticket-Show-Front/src/components/UserProfile/Profileuser.jsx
- Tiket-Show-Back/src/app.js
*prepare estados locales basicos
*deje  handlechange y submit
> Create event juan

- Ticket-Show-Front/src/components/UserProfile/Profileuser.jsx
Cambio de diseño
-estilos a terminar aun
-funcion que cambia las primeras letras de name y artist name a uppercase
> cambios en estilos

- Ticket-Show-Front/package-lock.json
- Ticket-Show-Front/package.json
- Ticket-Show-Front/src/Dashboard/TabListBase.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormLogin.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormRegister.jsx
- Ticket-Show-Front/src/components/NavBar/NavBar.jsx
- Ticket-Show-Front/src/components/UserProfile/Profileuser.jsx
- Tiket-Show-Back/index.js
validaciones del profile de user, validaciones del admin, y validaciones de correo en uso ok
>  validaciones

- Ticket-Show-Front/src/Dashboard/CardGridMapUsers.jsx
- Ticket-Show-Front/src/Dashboard/ChartDonutsUsers.jsx
- Ticket-Show-Front/src/Dashboard/TabListBase.jsx
graficos de usuarios graficos donut, solucion del bucle del dashboard
>  graficos de usuarios

- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
>  validaciones basicas

- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
> estilo validacion

- Ticket-Show-Front/src/components/CreateEvent/CreateEvent.jsx
ajustes en inputs para que el form no ocupe tanto espacio
-falta corregir: se deforma cuando aparecen validaciones
> cambios diseño

- Ticket-Show-Front/src/Views/Home/Home.jsx
- Ticket-Show-Front/src/components/Card/Card.jsx
- Ticket-Show-Front/src/components/CardContainer/CardsContainer.jsx
- Ticket-Show-Front/src/components/CreateEvent/EdiEvent.jsx
- Tiket-Show-Back/index.js
- Tiket-Show-Back/src/controllers/eventControllers/getControllers.js
modificaciones de filtros y desactivacion de cards
>  modif filtros y desact event

- Ticket-Show-Front/src/components/CreateEvent/EdiEvent.jsx
- Ticket-Show-Front/src/components/FormFirebase/FormRegister.jsx
detalles en el edit event con lista desplegable y form de registro q despache los usuarios de la db si el registro es existoso
>  detalles del editevent
